"""added projectupdate

Revision ID: 1dd716b25acf
Revises: 8aad0dc0fd2c
Create Date: 2023-04-15 14:42:05.939329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd716b25acf'
down_revision = '8aad0dc0fd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_update_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_update_timestamp'))

    op.drop_table('project_update')
    # ### end Alembic commands ###
