"""added title, refactored project

Revision ID: 78e728743978
Revises: 1dd716b25acf
Create Date: 2023-04-15 14:45:10.667618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e728743978'
down_revision = '1dd716b25acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=70), nullable=True))
        batch_op.add_column(sa.Column('desc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))
        batch_op.drop_index('ix_project_project_name')
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)
        batch_op.drop_column('project_name')
        batch_op.drop_column('project_link')
        batch_op.drop_column('project_desc')

    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_update', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_desc', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('project_link', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.VARCHAR(length=70), nullable=True))
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.create_index('ix_project_project_name', ['project_name'], unique=False)
        batch_op.drop_column('link')
        batch_op.drop_column('desc')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
