"""added photos

Revision ID: 88aaf7f0eb3e
Revises: 78e728743978
Create Date: 2023-04-15 23:36:30.830082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88aaf7f0eb3e'
down_revision = '78e728743978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_update_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['project_update_id'], ['project_update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_photo')
    # ### end Alembic commands ###
