"""add project

Revision ID: 8aad0dc0fd2c
Revises: 592503daff0b
Create Date: 2023-04-14 21:37:05.708287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aad0dc0fd2c'
down_revision = '592503daff0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=70), nullable=True),
    sa.Column('project_desc', sa.Text(), nullable=True),
    sa.Column('project_link', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_project_name'), ['project_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_name'))

    op.drop_table('project')
    # ### end Alembic commands ###
