"""added visit

Revision ID: a08ae3239cbf
Revises: 88aaf7f0eb3e
Create Date: 2023-05-14 15:13:00.114791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08ae3239cbf'
down_revision = '88aaf7f0eb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_to', sa.String(length=30), nullable=True),
    sa.Column('page_from', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit')
    # ### end Alembic commands ###
