"""added timestamp to visit table

Revision ID: dd633001cd1d
Revises: c28a1fe8dd11
Create Date: 2023-05-14 20:50:51.043997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd633001cd1d'
down_revision = 'c28a1fe8dd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_visit_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
